### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by spikry** [sensepost/ruler#1]
Hi

I did a git clone and downloaded ruler but now i have issues where i cannot run it. Can you assistance me please?

`root@spikry:~/ruler# go env

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build661526815=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

root@spikry:~/ruler# go run ruler.go -h
ruler.go:9:2: cannot find package "github.com/sensepost/ruler/autodiscover" in any of:
	/usr/lib/go-1.7/src/github.com/sensepost/ruler/autodiscover (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/autodiscover (from $GOPATH)
ruler.go:10:2: cannot find package "github.com/sensepost/ruler/mapi" in any of:
	/usr/lib/go-1.7/src/github.com/sensepost/ruler/mapi (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/mapi (from $GOPATH)
ruler.go:11:2: cannot find package "github.com/sensepost/ruler/utils" in any of:
	/usr/lib/go-1.7/src/github.com/sensepost/ruler/utils (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/utils (from $GOPATH)

root@spikry:~/ruler# go version
go version go1.7 linux/amd64
`

**Comment by staaldraad** [comment]
Hi

Looks like I should fix the README, I forgot to take into account Go and GOPATH. 
You have two options, 
either use "go get" instead of git clone: 
``` go get github.com/sensepost/ruler ```

OR put ruler in your GOPATH ```GOPATH="/root/go"```
```
mkdir /root/go/src/github.com /root/go/src/github.com/sensepost
mv /root/ruler /root/go/src/github.com/sensepost/
cd /root/go/src/github.com/sensepost/ruler
go run ruler.go -h
```

That should fix it, please let me know if it doesn't. I'll add pre-built binaries to the repo as well.
Thanks for testing it out!

**Comment by spikry** [comment]
Hi,

Running `go get github.com/sensepost/ruler` and setting the GOPATH `GOPATH="$HOME/go"` fixed the issue.
Thank you for the assistance.
