### ISSUE TITLE
error while using "--insecure" flag

### ISSUE THREAD

**Issue by 0xsauby** [sensepost/ruler#10]
I get the following error while using ruler with --insecure flag:
"Incorrect Usage: flag provided but not defined: --insecure"

My brute-force command line options were:
./ruler --domain domain.com brute --users users.txt --passwords password.txt --delay 0 --verbose --insecure

Am I missing something?

**Comment by staaldraad** [comment]
Hey @0xsauby 

```--insecure``` has been defined as a global flag, so you need to move it. It should be before "brute" (the sub-command) 

```
./ruler --domain domain.com --insecure brute --users users.txt --passwords password.txt --delay 0 --verbose
```

Still trying to figure out the best way to do the args for this. Should probably build a "console" when time allows.

**Comment by staaldraad** [comment]
I see that I screwed up the README and hence the confusion. 

Fixed this in https://github.com/sensepost/ruler/commit/e261155072ba4d4925a2c11df3721784bd02a313

**Comment by 0xsauby** [comment]
Awesome, thanks for a quick response. Leet research btw.
