### ISSUE TITLE
ERROR: 17:57:38 ruler.go:29: Address book support is currently limited to MAPI/HTTP

### ISSUE THREAD

**Issue by donjuanme** [sensepost/ruler#100]
hi

./ruler-linux64 --debug --nocache --verbose --rpc --url https://autodiscover.banana.org/autodiscover/autodiscover.xml -e mail@banana.org -u mail -p "sdfdsfsdf" abk dump -o banana.txt

[*] RPC/HTTP forced, trying RPC/HTTP
[*] Autodiscover step 0 - URL: https://autodiscover.banana.org/autodiscover/autodiscover.xml
[*] RPC URL set: https://mail.banana.org/rpc/rpcproxy.dll?d815808b-646a-4e43-94ce-60e9af457672@banana.org:6001
[*] Setting up channels
[+] Binding to RPC
[*] User DN:  /o=banana/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=3a5f4dca07014373931f3a3eef19f4f8-mail
[*] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
ERROR: 17:57:38 ruler.go:29: Address book support is currently limited to MAPI/HTTP
[*] And disconnecting from server

**Comment by staaldraad** [comment]
Hi

Accessing the address book via RPC/HTTP (`--rpc`) has not been implemented. This would require writing the RPC protocol used for the address book.

Address book access wasn't the main goal when writing Ruler and the effort required for the additional protocol did not seem worth it.

Best,

**Comment by donjuanme** [comment]
any idea how to go further here ?

root@server1:~# ./ruler-linux64 --debug --nocache --verbose --url https://autodiscover.banana.org/autodiscover/autodiscover.xml -e mail@banana.org -u mail -p "sdfdsfsdf" abk list

[*] Autodiscover step 0 - URL: https://autodiscover.banana.org/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://mail.banana.org/mapi/emsmdb/?MailboxId=d815808b-646a-4e43-94ce-60e9af457672@banana.org
[*] MAPI AddressBook URL found:  https://mail.banana.org/mapi/nspi/?MailboxId=d815808b-646a-4e43-94ce-60e9af457672@banana.org
ERROR: 23:18:18 ruler.go:29: mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response
root@server1:~#

**Comment by donjuanme** [comment]
root@H:~/pentest/ruler# ./ruler-linux64 --domain tesdomain --email anadmin@testdomain.com --username ahadmin --password anadmin123 --nocache c
[+] Retrieving MAPI/HTTP info
ERROR: 23:42:10 ruler.go:29: mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response

**Comment by donjuanme** [comment]
root@testdomain:~/pentest/ruler# ./ruler-linux64 --verbose --debug --nocache --domain testdomain --email anadmin@testdomain.com --username anadmin --password admin123 --nocache c

[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://autodiscover.testdomain.com/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://mail.testdomain.com/mapi/emsmdb/?MailboxId=3a70de89-0651-41e9-96b0-ba6bcbf93fb0@testdomain.com
[*] MAPI AddressBook URL found:  https://mail.testdomain.com/mapi/nspi/?MailboxId=3a70de89-0651-41e9-96b0-ba6bcbf93fb0@testdomain.com
ERROR: 23:45:50 ruler.go:29: mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response
