### ISSUE TITLE
ERROR: 23:18:18 ruler.go:29: mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response

### ISSUE THREAD

**Issue by donjuanme** [sensepost/ruler#101]
any idea how to go further here ?

`root@server1:~#` ./ruler-linux64 --debug --nocache --verbose --url https://autodiscover.banana.org/autodiscover/autodiscover.xml -e mail@banana.org -u mail -p "ssdsdsdsd" abk list
[*] Autodiscover step 0 - URL: https://autodiscover.banana.org/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://mail.banana.org/mapi/emsmdb/?MailboxId=d815808b-646a-4e43-94ce-60e9af457672@banana.org
[*] MAPI AddressBook URL found:  https://mail.banana.org/mapi/nspi/?MailboxId=d815808b-646a-4e43-94ce-60e9af457672@banana.org
ERROR: 23:18:18 ruler.go:29: mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response
root@server1:~# `

**Comment by peyu123** [comment]
i have the same issue ? any ideas ?
