### ISSUE TITLE
 get attachments

### ISSUE THREAD

**Issue by mary9988** [sensepost/ruler#102]
Hi 
now i am studying mapi  and looking for a way to download mail now. i have read the code , found function GetAttachments is not completed .i tried to get attachment id but there's nothing i can do about it, can you fix the problem?

**Comment by staaldraad** [comment]
Hi

I used the Exchange documentation to create the requests, according to the docs that should be correct for receiving a list of attachments but as the error message states, the server I was testing against responded that it didn't understand the Rop request.

There is however code to download individual attachments (you just don't have the ability to list to attachments). Have a look at this code in `notruler`: https://github.com/sensepost/notruler/blob/master/notruler.go#L335

It calls [OpenAttachment](https://github.com/sensepost/ruler/blob/master/mapi/mapi.go#L1562) - maybe you can use this code as a starting point for getting this working.

Best

**Comment by petermolnar11** [comment]
> Hi
> now i am studying mapi and looking for a way to download mail now. i have read the code , found function GetAttachments is not completed .i tried to get attachment id but there's nothing i can do about it, can you fix the problem?

Use OpenAttachment function with message ids: 0, 1, 2, 3, ... When you receive error NOT_FOUND you have to stop calling OpenAttachment (because you read all attachments or there are no attachs)
