### ISSUE TITLE
Access denied. Check your credentials - Exchange Online

### ISSUE THREAD

**Issue by pawp81** [sensepost/ruler#105]
Is Ruler supposed to work against Exchange Online mailbox? I am running "check" command and getting Access Denied. (same if I try --basic). 
Target user is not enabled for MFA and basic auth isn't blocked with Conditional Access.
./ruler --username "john.doe@contoso.com" --password "Password1" --email "john.doe@contoso.com" check

[+] Retrieving MAPI/HTTP info
ERROR: 19:39:40 ruler.go:29: The autodiscover service request did not complete.
Access denied. Check your credentials

**Comment by staaldraad** [comment]
👋 Hi

I'm not sure if Exchange Online is referring to Office365? Ruler should work fine against that; [https://github.com/sensepost/ruler/wiki#office365](https://github.com/sensepost/ruler/wiki#office365) 

If this is something different, it might require manually specifying the autodiscover URL to auth against or using a config file: [https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file](https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file)
