### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by rmaksimov** [sensepost/ruler#119]
There is a version mismatch between the source code (2.2.2) and the last release (2.3)

**Comment by staaldraad** [comment]
Thanks for all the updates! Updated to 2.4.0: [https://github.com/sensepost/ruler/releases/tag/2.4.0](https://github.com/sensepost/ruler/releases/tag/2.4.0)

```
VERSION:
   2.4.0

DESCRIPTION:
            _
 _ __ _   _| | ___ _ __
| '__| | | | |/ _ \ '__|
| |  | |_| | |  __/ |
|_|   \__,_|_|\___|_|

A tool by @_staaldraad and @sensepost to abuse Exchange Services.


AUTHORS:
   Etienne Stalmans <@_staaldraad>
   Roman Maksimov <@rmaksimov>
```
