### ISSUE TITLE
Unable to run ruler

### ISSUE THREAD

**Issue by M-Ather** [sensepost/ruler#120]
Hello:
Thanks for the excellent tool you developed for abusing Exchange Services. I have setup the ruler.go and trying to execute the command but it just returns the help page every time without showing any error. I tried to search for the solution on the wiki page and internet but no success. I am using ruler on Windows X, my GOPATH value is c:\go\bin Can you please look at the following command and guide what am I doing wrong:

C:\Users\Dell\go\src\github.com\sensepost\ruler>go run ruler.go --domain domain.com -users validemail@domain.com b
This command results in following error: Incorrect Usage. flag provided but not defined: -users

And when I try to execute this Command: C:\Users\Dell\go\src\github.com\sensepost\ruler>go run ruler.go --domain domain.com --username validemail@domain.com -b
The above commands just outputs the help of ruler
Please help.

**Comment by staaldraad** [comment]
Hi @M-Ather 

Thank you for trying it out! It looks like your `GOPATH` and setup is correct, Ruler is executing :) The trouble you are running into is with the CLI arguments. Have you had a look at the examples in the Wiki https://github.com/sensepost/ruler/wiki/Brute-Force?

You seem to be trying a brute-force, in that case you are looking for:
```
go run ruler.go --domain targetdomain.com brute --users /path/to/user.txt --passwords /path/to/passwords.txt
```

Note how *brute* is not a dash-argument, and that all the other arguments require double dashes `--`

**Comment by M-Ather** [comment]
Perfect. Worked as expected
