### ISSUE TITLE
Rule name display is not complete

### ISSUE THREAD

**Issue by daikerSec** [sensepost/ruler#121]
Rule name display is not complete when ruler display. For example, I have a Rule Name called AllStaff, which will be displayed as llStaff
![ruler](https://user-images.githubusercontent.com/26897699/81905371-3234c000-95f7-11ea-8a67-92a6a9ccd8ab.jpg)

**Comment by staaldraad** [comment]
Hi

Is this with the latest version? There was a bug in rule parsing before, this might be a regression. Otherwise it looks like the first rule isn't printing correctly either, that might have something to do with it.
Could you please provide the version of Ruler you are using, and whether this is MAPI/HTTP or RPC/HTTP.

**Comment by daikerSec** [comment]
您好，我在2.2.2以及2.4.0 都遇到了这个问题。
![image](https://user-images.githubusercontent.com/26897699/82773865-bd267d80-9e75-11ea-9aba-b406eb07ad11.png)
![image](https://user-images.githubusercontent.com/26897699/82773891-d8918880-9e75-11ea-9b71-dafe5baa0714.png)
这是我使用的命令
```bash
ruler_windows_amd64.exe --insecure --url https://autodiscover.xx.xx.xxx/autodiscover/autodiscover.xml  --email xxx@xxx.xxx -u xxx -p xxxx --verbose --debug display
```

**Comment by daikerSec** [comment]
> Hello, I have encountered this problem in both 2.2.2 and 2.4.0.
> 
> ![image](https://user-images.githubusercontent.com/26897699/82773865-bd267d80-9e75-11ea-9aba-b406eb07ad11.png)
> ![image](https://user-images.githubusercontent.com/26897699/82773891-d8918880-9e75-11ea-9b71-dafe5baa0714.png)
> 
> This is the command I used
> 
> ```shell
> ruler_windows_amd64.exe --insecure --url https://autodiscover.xx.xx.xxx/autodiscover/autodiscover.xml  --email xxx@xxx.xxx -u xxx -p xxxx --verbose --debug display
> ```

@staaldraad

**Comment by staaldraad** [comment]
Hey @daikerSec 

This seems like it might be an issue with unicode. Do the Rule IDs still print correctly and are usable directly? I've got no way to test this unfortunately. It might also be worth trying in a Linux terminal or another terminal emulator for Windows, just to rule out that it isn't an output problem

**Comment by staaldraad** [comment]
I think this might be due to the bug pointed out in #122 

I've drafted a release that fixes it, if you could give it a try please @daikerSec : https://github.com/sensepost/ruler/releases/tag/untagged-ec15daae6305be4005f2
