### ISSUE TITLE
RPC Connection refused

### ISSUE THREAD

**Issue by b4cktr4ck2** [sensepost/ruler#125]
Hello,

I'm currently attempting to run ruler against an Exchange 2010 host, and no matter which ruler module I choose, I receive the following error: 
```
ERROR: 10:54:02 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. 
mapi: a transport layer error occurred. Couldn't setup RPC channel - RPC Setup
Err: dial tcp :443: connect: connection refused
```
Running it with the verbose flag gives me the following output:
```
[+] Found cached Autodiscover record. Using this (use --nocache to force new lookup)
[*] Authentication scheme is Basic
[*] RPC URL set: /rpc/rpcproxy.dll?exchange.testing.com:6001
[*] Setting up channels
```
Followed by the error. I tested this on a Mac and a Linux OS as well and can confirm the error is the same on both.

My command specifies a custom autodiscover URL, the e-mail address, and the username and password.

Please let me know if there's any other information you require and I'll do my best to provide it.

Thank you!

**Comment by staaldraad** [comment]
Hi @b4cktr4ck2 

It looks like the RPC URL being returned by the autodiscover record is empty. I would expect this 
`[*] RPC URL set: /rpc/rpcproxy.dll?exchange.testing.com:6001` 
to be set to something like 
`[*] RPC URL set: https://exchnage.testing.com/rpc/rpcproxy.dll?exchange.testing.com:6001`

Either the test server doesn't have RPC enabled, or is not configured correctly. You can try manually giving the RPC URL using the config file option: https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file

**Comment by b4cktr4ck2** [comment]
Thanks for the reply @staaldraad - looks like the server didn't have RPC configured properly. I'll go ahead and close this now, appreciate the insight!
