### ISSUE TITLE
Valid creds not working

### ISSUE THREAD

**Issue by leebaird** [sensepost/ruler#129]
Kali Linux completely patched.
go version go1.15.8 linux/amd64

Example 1
go run ruler.go --email joe.smith@acme.org
Password:
[enter password]
[+] Retrieving MAPI/HTTP info
ERROR: [time stamp] ruler.go:29: The autodiscover service request did not complete.
Access denied. Check your credentials
exit status 255

Example 2
go run ruler.go --domain acme.org --users users.txt --passwords passwords.txt --delay 0 -v
[x] Failed: joe.smith@acme.org:password

**Comment by staaldraad** [comment]
Hi

It is likely that you need to either try with the `--basic` flag to force basic auth, or the username needs to be set as a username and not an email. Something like `--username joe.smith --email joe.smith@acme.org`. For troubleshooting this, go to the autodiscover end-point using a browser and check the network requests. Are you prompted for Basic, or NTLM auth? Does it use the email address or the username.

Finally, if none of that works, try switching between versions of Ruler such as [2.2.0](https://github.com/sensepost/ruler/releases/tag/2.2.0) and [2.4.0](https://github.com/sensepost/ruler/releases/tag/2.4.0) which have slightly different logic for  auth decisions.
