### ISSUE TITLE
Is there a way to output valid credentials to a file for the brute force?

### ISSUE THREAD

**Issue by SimplyDope** [sensepost/ruler#131]
Hi there,

Sorry might be a stupid question, but is there a way to output valid creds to a file with the brute option.

**Comment by staaldraad** [comment]
Hey @SimplyDope 

Nope, but all the output is on stdout, so you can just redirect to a file:

```
./ruler brute [flags] > outfile.txt
```

You can then parse that file the way you wish, for example using `grep` to only show success
