### ISSUE TITLE
x509 error: certificate signed by unknown authority

### ISSUE THREAD

**Issue by steveburton** [sensepost/ruler#133]
I am new to certificates and get the following when first executing ruler-win64:

C:\Users\Administrator\Downloads>ruler-win64 --email bridgette.hutchinson@https://???????????????????????/owa --verbose check
Password:
ERROR: 08:30:50 autodiscover.go:204: CreateFile ./logs/bridgette_hutchinson_https://???????????????????????/owa.cache: The filename, directory name, or volume label syntax is incorrect.
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://???????????????????????/owa
[*] Autodiscover step 1 - URL: https://???????????????????????/owa
[*] Autodiscover step 2 - URL: https://???????????????????????/owa
ERROR: 08:30:51 ruler.go:29: The autodiscover service request did not complete.
Post "https://???????????????????????/owa": Get "https://???????????????????????/owa": x509: certificate signed by unknown authority

Any pointers appreciated.

**Comment by steveburton** [comment]
No response.

**Comment by wadim1281** [comment]
????
