### ISSUE TITLE
The autodiscover service request did not complete.

### ISSUE THREAD

**Issue by axingde** [sensepost/ruler#134]
The following error is prompted when creating the form:
![image](https://user-images.githubusercontent.com/65204372/166871322-44e91f14-46c5-4c21-bbcf-2c1918beb0b1.png)

**Comment by staaldraad** [comment]
please see https://github.com/sensepost/ruler/issues/124#issuecomment-850815778

Autodiscover is best effort and might not always work. This can be worked around by using `--url` with the correct URL to the exchange services
