### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by b10w** [sensepost/ruler#24]
Hello there!

I'm using the latest dev build and am receiving this error when trying to display rules. I get a similar runtime error in other use cases as well. I've tried different combinations of switches and usernames to see if that was the issue, but no luck. Hoping maybe you can shed a bit of insight into this!

```
[*] Autodiscover step 0 - URL: [redacted]
[*] RPC URL set: [redacted]
[*] Setting up channels
panic: runtime error: slice bounds out of range

goroutine 4 [running]:
panic(0x33eb20, 0xc4200100e0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/staaldraad/go-ntlm/ntlm.ParseChallengeMessage(0x54b580, 0x0, 0x0, 0xc420075818, 0x8, 0x0)
	/home/staaldraad/Go/gopath/src/github.com/staaldraad/go-ntlm/ntlm/message_challenge.go:59 +0x7e1
github.com/sensepost/ruler/rpc-http.setupHTTP(0x39aa62, 0xb, 0xc4202fc7e0, 0x6e, 0x40101, 0xc4200296d8, 0xc4200296a0, 0x4438c, 0xc4200296d8)
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/rpc-http/rpctransport.go:121 +0x10a1
github.com/sensepost/ruler/rpc-http.RPCOpen(0xc4202fc7e0, 0x6e, 0xc420421e00, 0xc420421e60, 0xc42011a550, 0xe1b1)
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/rpc-http/rpctransport.go:170 +0x7c
created by github.com/sensepost/ruler/mapi.mapiConnectRPC
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/mapi/mapi.go:162 +0x18d
```

**Comment by staaldraad** [comment]
Hey!  

RPC is going to be the death of me :)

* Could you check the autodiscover.xml (in ```logs/email_address.cache```) and see if the AuthPackage is set to **Ntlm**: ```  <AuthPackage>Ntlm</AuthPackage> ```

* Are you using the --hash or password for authentication? 
* Would you be able to build from source or are you limited to using the pre-built?

I've just pushed an updated binary to the "Dev Fixes" release: https://github.com/sensepost/ruler/releases/tag/v2.0.18

Maybe this works?

**Comment by b10w** [comment]
Haha! Sorry, man!

- Can you elaborate on the first point? I'm already using the pre-built dev release you have linked in your previous message.

- I'm using --password. 

- I can certainly _try_ if that'll help with troubleshooting! Go is not a language I'm fluent in, so I opted for the dev builds instead :)

Actually, my situation may be a tad unique - but don't really want to put all of it out in open here. Have an email address where I can explain things a bit further?

**Comment by staaldraad** [comment]
Perfect, ping me at etienne "at" sensepost.com - also prefer to troubleshoot that way.
I'm sure we can get this to work, edge cases are great :)

**Comment by staaldraad** [comment]
I'm going to add a check to bail out, if a 503 or similar is returned, before trying to authenticate with NTLM.
This seems to be specific to the deployment of this Exchange instance
