### ISSUE TITLE
Forms is crashing Office 2016 and preventing it to restart in normal mode

### ISSUE THREAD

**Issue by flacostec** [sensepost/ruler#34]
I did what is written in the readme with > CreateObject("Wscript.Shell").Run "calc.exe", 0, False and it crashed outlook completely. I had to restart it in safe mode. 

EDIT: After I deleted the rule and re-added it, it worked.

**Comment by staaldraad** [comment]
I'll have to dig into this a little bit. I had some crashing forms during dev but they were solid by the time I pushed public. 

I take from your edit that it's working now?

One possibility is having two forms with the same suffix. Outlook doesn't allow this, so it leads to forms failing as Outlook doesn't know which one to choose. -- I'll build in some checks to prevent this.

**Comment by staaldraad** [comment]
Added checks to ensure no duplicate forms
