### ISSUE TITLE
Getting "This action is not available in the current mode" after adding a rule that spawn calc.exe (o365)

### ISSUE THREAD

**Issue by flacostec** [sensepost/ruler#35]
I've tried different combination : 
> --location "\\\\localhost\\c$\\windows\\system32\\calc.exe"
> --location "c:\windows\system32\calc.exe"

EnableUnsafeClientMailRules is not set and I'm using Office 2016.

**Comment by staaldraad** [comment]
For Office 2016, the **EnableUnsafeClientMailRules** has to be set. to **1**. Even if you are running local applications. 

The key is here:
```
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\Security]
"EnableUnsafeClientMailRules"=dword:00000001
```

This key re-enables the _RunScript_ and _RunApplication_ rules.
