### ISSUE TITLE
Any chance to implement a Upstream proxy?

### ISSUE THREAD

**Issue by pimps** [sensepost/ruler#38]
During my tests, setting up the http_proxy and https_proxy environment variables to configure upstream proxy or just using proxychains didn't made the tool work through the proxy as expected...

Can you implement a --proxy "http://user:pass@proxy.server.com" on the tool?

Thanks.

**Comment by pimps** [comment]
With Proxychains:

root@kali:~# proxychains ./ruler-linux64 --o365 -u "email@corporate.com" -p 'mypass123' -e "email@corporate.com" --insecure --nocache --verbose add -n "hacks" -t "p0wn3d" --send
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Autodiscover step 0 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 1 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 2 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
ERROR: 2017/06/05 13:09:48 The autodiscover service request did not complete.
Post https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: Get https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: dial tcp: lookup autodiscover-s.outlook.com on 192.168.201.10:53: no such host

Setting http_proxy and https_proxy:

root@kali:~# ./ruler-linux64 --o365 -u "email@corporate.com" -p 'mypass123' -e "email@corporate.com" --insecure --nocache --verbose add -n "hacks" -t "p0wn3d" --send
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Autodiscover step 0 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 1 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 2 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
ERROR: 2017/06/05 14:27:30 The autodiscover service request did not complete.
Post https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: Get https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: dial tcp: lookup autodiscover-s.outlook.com on 192.168.201.10:53: no such host

Setting http_proxy and https_proxy and inserting the entries on /etc/hosts:

root@kali:~# cat /etc/hosts
127.0.0.1	localhost
40.101.125.34    outlook.office365.com
40.101.50.162    autodiscover-s.outlook.com

 root@kali:~# ./ruler-linux64 --o365 -u "email@corporate.com" -p 'mypass123' -e "email@corporate.com" --insecure --nocache --verbose add -n "hacks" -t "p0wn3d" --send
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Autodiscover step 0 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 1 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] Autodiscover step 2 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
ERROR: 2017/06/05 14:15:14 The autodiscover service request did not complete.
Post https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: Get https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

------

My scenario: the exchange of my client is on the Office365 but you can access it only if you're connected to VPN or on the internal network... Once in the internal network, communication with internet only happens using the upstream proxy.

**Comment by staaldraad** [comment]
Ok, this is super frustrating...

So the following seems to work, but then nothing actually goes through the proxy:
``` https_proxy=127.0.0.1:8080 ./ruler --email x@y.com ```

The reason I say it "seems to work" is that setting it up like that ended up with a cert error for *autodiscover_s.outlook.com* - so it's working.. NOT..

I've got it working now by forcing a proxy object into the http.client. I'll add that in as a **--proxy** option now and push for you to test.

**Comment by staaldraad** [comment]
![screenshot from 2017-06-07 10-15-20](https://user-images.githubusercontent.com/4200832/26868830-90675244-4b6a-11e7-92eb-f3dc0998976a.png)

Landing this in the [debug](https://github.com/sensepost/ruler/tree/debug) branch for now. I've also added some binaries to the [releases](https://github.com/sensepost/ruler/releases/tag/2.1.7)

**Comment by pimps** [comment]
Hey mate,

First of all, thanks for put that functionality on your tool and for expend some time doing that. I just tested it but unfortunately still not working as I expect... for some reason the application is resolving the name with the nameserver instead pass it to the proxy to be resolved there... Dunno if it's a application config or is my failure in configure the proxy properly... The fact is: other applications like wget and curl get the proxy configuration and forward the name resolution properly... but for some reason ruler is using the nameserver instead forward the name resolution to the proxy...
