### ISSUE TITLE
ADFS integrated Office 365 authentication

### ISSUE THREAD

**Issue by blark** [sensepost/ruler#39]
First of all, great tool - thanks for your hard work.

I've got a client with ADFS integration, so requests to `wget autodiscover.client.com` end up first getting redirected to `https://outlook.office365.com/owa/?realm=client.com&vd=autodiscover` and then subsequently to  `https://login.microsoftonline.com/login.srf?<REDACTED>` and then finally there is one more redirect to the client's own server for authentication before getting sent back to a valid Outlook 365 session. 

I noticed that there is a --cookie option and I'm thinking that is one way to attack the issue, but I'm not sure which cookie I should set as there are about 15. So I guess my first question is, would it be possible to implement loading of a cookie file so I could just save all the cookies and provide a valid session? 

I was investigating the config file option as well but the details required seem to be missing from Office 365. I guess I could also set up burp to see what's going on--that's on my todo list at the moment. 

Am I doing something wrong or is this a limitation of ruler at the moment? Thanks!

**Comment by staaldraad** [comment]
Hi, thanks so much!

Interesting that the autodiscover.client.com redirects to the OWA interface on Office365. If you do a wget to autodiscover.client.com/autodiscover/autodiscover.xml - do you get a redirect to either autodiscover-s.outlook.com or autodiscover.outlook.com?

Ruler should work seamlessly with ADFS, it was the very first deployment I did all the development on. If you do ```./ruler --email a@b.com --username p --verbose check``` you should be able to see some of the steps taken by ruler to try resolve. There should be a "redirected to" message in there somewhere.

The --cookie option would take all 15 cookies, the format being cookie1=value;cookie2=value , but I do understand that 15 large cookies on the cmdline will be a mess! I can add this as a config option in the config file.

Thanks for getting in touch and hopefully we get this to working

**Comment by blark** [comment]
Hi, thanks for the quick response! Here's the output of that wget... 

```
wget autodiscover.CLIENT.COM/autodiscover/autodiscover.xml
--2017-06-16 08:53:04--  http://autodiscover.CLIENT.COM/autodiscover/autodiscover.xml
Resolving autodiscover.CLIENT.COM (autodiscover.CLIENT.COM)... 40.97.149.152, 40.97.155.184, 40.97.161.40, ...
Connecting to autodiscover.CLIENT.COM (autodiscover.CLIENT.COM)|40.97.149.152|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml [following]
--2017-06-16 08:53:04--  https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
Resolving autodiscover-s.outlook.com (autodiscover-s.outlook.com)... 40.97.130.210, 40.97.124.210, 40.97.124.34, ...
Connecting to autodiscover-s.outlook.com (autodiscover-s.outlook.com)|40.97.130.210|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

**Comment by staaldraad** [comment]
Ok perfect, it looks like Ruler might need an update. My "FederatedAuth" test so far have been where auth happens against the on-premise exchange, which hands off to o365 to do the rest. Funny enough, I was looking at the *urn:federation:MicrosoftOnline* yesterday as I research Lync. 

I'm going to try setup a test environment for this, but in the meantime, you could try one of the other options for auth.

Three options to try:
1.) ```./ruler --email user@client.com --verbose check```
2.) ```./ruler --email user@client.com --username user@client.com --basic --verbose check```
2.) ```./ruler --email user@client.com --username username --basic --verbose check```

Another challenge, thanks!

**Comment by staaldraad** [comment]
On second thoughts, looking at this again, Ruler should work out the box with this. The description you've given seems to be exactly the same as on my test domain. The flow looks identical:

```
$ wget http://autodiscover.0x04.cc/autodiscover/autodiscover.xml                                                       
--2017-06-18 17:46:15--  http://autodiscover.0x04.cc/autodiscover/autodiscover.xml
Resolving autodiscover.0x04.cc (autodiscover.0x04.cc)... 40.101.54.120, 40.101.124.8, 40.101.124.24, ...
Connecting to autodiscover.0x04.cc (autodiscover.0x04.cc)|40.101.54.120|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml [following]
--2017-06-18 17:46:15--  https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
Resolving autodiscover-s.outlook.com (autodiscover-s.outlook.com)... 40.101.72.226, 40.101.72.130, 40.101.12.114, ...
Connecting to autodiscover-s.outlook.com (autodiscover-s.outlook.com)|40.101.72.226|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

If you check the headers with *curl*:

```
$ curl -L -i http://autodiscover.rotala.co.uk/autodiscover/autodiscover.xml 
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-cache
Pragma: no-cache
Location: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
Server: Microsoft-IIS/8.5
X-FEServer: VI1PR08CA0189
X-RequestId: 897833a8-bad1-4d69-804b-308d0585401f
X-Powered-By: ASP.NET
X-FEServer: VI1PR08CA0189
Date: Sun, 18 Jun 2017 16:49:07 GMT
Connection: close
Content-Length: 0

HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/8.5
request-id: c2d832ee-9ec1-43dd-9a48-0d887a49a3a0
X-SOAP-Enabled: True
X-WSSecurity-Enabled: True
X-WSSecurity-For: Logon
X-FederationTrustTokenIssuerUri: urn:federation:MicrosoftOnline
X-WSSecurity-SymmetricKey-Enabled: True
X-WSSecurity-X509Cert-Enabled: True
X-OAuth-Enabled: True
WWW-Authenticate: Basic Realm=""
X-Powered-By: ASP.NET
X-FEServer: AM5P190CA0008
Date: Sun, 18 Jun 2017 16:49:07 GMT
Content-Length: 0

```
_________
I'm pretty sure your client's auth will follow an identical path. So either of the following will work:

```./ruler --email target@client.com --o365 check```
 or
```./ruler --email target@client.com check```

Hope this helps

**Comment by blark** [comment]
First thing I tried, I will try again and copy the output when I'm at my work system. Thanks!

**Comment by blark** [comment]
I tried every iteration I could thing of of the following

```
2.) ./ruler --email user@client.com --username user@client.com --basic --verbose check
3.) ./ruler --email user@client.com --username username --basic --verbose check
```

nothing seems to be working. Can't get past the first request, always ends in status 401. I tried:

```
--email user@client.com --username user@client.com
--email user@client.com --username username --domain domain
--email user@client.com --username domain\\username 
```

Not quite sure where to go from that... Thanks for your help.

**Comment by staaldraad** [comment]
It's definitely trying to do the initial auth directly against O365, in which case I've always seen it using basic auth with: emailaddress:password

The SSO could be configured to enforce sign-on using a SAML token and ruler doesn't support that. Unfortunately I don't have a test domain with ADFS configured, otherwise I'd try and whip up a solution asap. I'm on a long running project for the next two weeks but hopefully I can find sometime in between to get to this. I fear this might be too late for you to use it in your assessment though.

Could you try hitting this URL in your browser: https://outlook.office365.com/mapi/emsmdb/
Then authenticating with a valid email address and password? If that works, then you should be able to use the --config option from Ruler and bypass autodiscover :)

**Comment by arabs1338** [comment]
Please fix the problem ruler wrong www-authenticate header :((
