### ISSUE TITLE
Can create rules but receive an Invalid HTTP response: [HTTP/1.1 401 Unauthorized] when creating an Outlook form

### ISSUE THREAD

**Issue by dimpol** [sensepost/ruler#40]
./ruler-linux64 --verbose --domain "mydomain" --username Administrator --hash 49623ccc820122ab49b3f0fxxxxxxxxx --email administrator@domain --url https://exchange.domain.com/autodiscover/autodiscover.xml --insecure display

[+] Found cached Autodiscover record. Using this (use --nocache to force new lookup)
[*] RPC URL set: http://exchange.domain.com/rpc/rpcproxy.dll?433c3f63-8aef-4136-b5d3-056bc8b237d2@domain.com:6001
[*] Setting up channels
[+] Binding to RPC
[*] User DN:  /o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=60837e670da647f18aab23e43a167ee0-Administrator
[+] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[+] Retrieving Rules
[+] No Rules Found
[*] And disconnecting from server

The above works and in general i can create any malicious rule i want.

------------------------------

Although, i have issues with creating a malicious Outlook form. Specifically, I receive the following.

ERROR: 2017/07/01 12:44:54 RPC Timeout
ERROR: 2017/07/01 12:44:54 mapi: a transport layer error occurred. An error occurred setting up RPC. Invalid HTTP response: [HTTP/1.1 401 Unauthorized]

The credentials i supply are correct and i as mentioned above i can create rules successfully. Can you help me debug this difference in behavior between rules and forms?

**Comment by staaldraad** [comment]
Hey!

I'm not to sure why this would be the case. The two functions use the same authentication/connect mechanism. The code paths only diverge post authentication, so this should not be happening at all.

Could you please post the forms command you are using, I'll need to try and replicate this behaviour. Honestly doesn't make sense to me.

You could also try using the ```--config``` option with a config.yml but I don't think this would make a difference. Finally, in releases there is a *debug* build, you could use that with ```--debug``` and we could try see why the auth is failing.

**Comment by staaldraad** [comment]
I've tested and can't reproduce this. A review of the code also doesn't show any reason why this would be the case. Auth happens before selecting "rules" or "forms" - so these options should not result in different authentication results
