### ISSUE TITLE
The autodiscover service request did not complete.

### ISSUE THREAD

**Issue by mpgn** [sensepost/ruler#42]
Hello

I always get this error : 
```
go run ruler.go --email demo@test.fr form display
Password: 
[+] Retrieving MAPI/HTTP info
ERROR: 2017/07/25 12:17:08 The autodiscover service request did not complete.
Error in autodiscover response, XML syntax error on line 14: invalid character entity &subset (no semicolon)
exit status 255
```

Any idea ?

**Comment by staaldraad** [comment]
Hi!

Sure thing, I think what is happening is Ruler is getting a response that it believes might be an autodiscover end-point (auth, followed by a 200). But it isn't actually a valid autodiscover response.

To verify, you can use: ```go run ruler.go --email demo@test.fr --verbose check``` 
this will show which URL Ruler tries to use. You can then try load the page in your browser and if you get a response similar to this:
```
<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
    <Error Time="21:25:04.8897083" Id="4130155072">
      <ErrorCode>600</ErrorCode>
      <Message>Invalid Request</Message>
      <DebugData />
    </Error>
  </Response>
</Autodiscover>
```

Then the URL is valid and there is an issue with Ruler, which we can try debug. If you get any other page, it means that is an invalid autodiscover end-point.

If the end-point is not a valid Autodiscover record, you can manually specify the autodiscover URL:

``` go run ruler.go --email demo@test.fr --url https://autodiscover.demo.fr/autodiscover/autodiscover.xml check```

^ you will need to set the URL to a valid autodiscover end-point.

Finally, if the domain you are targeting doesn't have autodiscover enabled, you can try the steps here: https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file

Good luck!

**Comment by VirtualSeeker** [comment]
hi, the ruler crashes when i test. Here is the info print:

**Comment by staaldraad** [comment]
Hi!

Thanks for the report!

Could you please check that you have the latest version of Ruler? The location of the crash doesn't make sense when I look in the master branch. That location is ```config.Email = yamlConfig.Email``` which should be unreachable using the command you have used.

If you are on the latest branch, please try visit the URL given in Autodiscover Step 2
```[*] Autodiscover step 2 - URL: http://autodiscover.xxxxx.com/autodiscover/autodiscover.xml```

And authenticate, you should then receive a page similar to this:
```
<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
    <Error Time="21:25:04.8897083" Id="4130155072">
      <ErrorCode>600</ErrorCode>
      <Message>Invalid Request</Message>
      <DebugData />
    </Error>
  </Response>
</Autodiscover>
```

**Comment by VirtualSeeker** [comment]
hi, staaldraad. Thanks for your support. I update ruler to the latest and it doesn't crash any more. But there are problems. Here is the log info:
xxxx@xxxx-pc:~/go/src/github.com/sensepost/ruler$ go run ruler.go --domain example.com --username username --password password --email username@example.com   --verbose check
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://example.com/autodiscover/autodiscover.xml
ERROR: 2017/08/15 18:48:53 XML syntax error on line 10: invalid UTF-8
[*] Autodiscover step 1 - URL: https://autodiscover.example.com/autodiscover/autodiscover.xml
[*] Autodiscover step 2 - URL: http://autodiscover.example.com/autodiscover/autodiscover.xml
ERROR: 2017/08/15 18:48:55 The autodiscover service request did not complete.
Post http://autodiscover.example.com/autodiscover/autodiscover.xml: Get https://autodiscover.example.com/autodiscover/autodiscover.xml: stopped after 10 redirects
exit status 255

when i open this url http://autodiscover.example.com/autodiscover/autodiscover.xml in chrome, some exceptions happen and it says :

This page isn’t working

autodiscover.example.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

it seems that there is something wrong with the example.com. And I try to clear cookies but it doesn't make any sense. How can i solve this problem? Thanks for your help and support.

**Comment by staaldraad** [comment]
Ah, it's one of those frustrating situations where the autodiscover service is configured differently from the specification or has a misconfiguration. You'll need to "hunt" for the autodiscover end-point and provide that to ruler.

Possible locations:
http://example.com/autodiscover/autodiscover.xml
https://mail.example.com/autodiscover/autodiscover.xml
https://owa.example.com/autodiscover/autodiscover.xml
https://webmail.example.com/autodiscover/autodiscover.xml

If you try these in the browser, and get an auth prompt, you can see if you hit upon one that gives you the expected XML output I mentioned earlier.

You can then use that URL with ruler:

```go run ruler.go --username xxx --password xxx --email xxx@example.com --url https://theurl.you.found/autodiscover/autodiscover.xml --verbose check```

:) hope you get lucky!

**Comment by VirtualSeeker** [comment]
hi, staaldraad. Thank you and i tried these urls you offered, but they all did not work. And i tried to use Test E-mail AutoConfiguration of OutLook to find out the autodiscover end-point, however it failed too. And I don't how to do next and maybe i should give up now. By the way, can you give me some tips of which mail server provide autodiscover service normally and it can be registered free? Thanks.

**Comment by staaldraad** [comment]
Ruler uses the exact same steps as Outlook, so if outlook is failing then the domain definitely doesn't have autodiscover setup externally :disappointed: 

For testing, outlook.com is free and it is basically the free version of o365. So anything that works there, will work in Office 365. The other options are to use the free trial you can get with Azure, however that requires setting up a domain, exchange etc. 

I think Office365 might have a 30 day trial as well. Outlook is really the best option if you want easy setup and a free service

**Comment by VirtualSeeker** [comment]
Oh, my god. Thanks, staaldraad. I registered in outlook.com and succeeded in accessing my outlook email using ruler.  i have bee trying ruler for almost two weeks , and finally today i succeed with your help and support. You are too great. Thank you and may you my best wishes.

xxxx@xxxx-pc:~/go/src/github.com/sensepost/ruler$ go run ruler.go --domain outlook.com --username 
username --password password --email username@outlook.com   --verbose check
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://outlook.com/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://outlook.office365.com/mapi/emsmdb/?MailboxId=xxxxxxxxx@outlook.com
[*] MAPI AddressBook URL found:  https://outlook.office365.com/mapi/nspi/?MailboxId=xxxxxxxxx@outlook.com
[*] User DN:  /o=First Organization/ou=Exchange Administrative Group(FYDIBOHF23SPDLT)/cn=Recipients/cn=00037FFE0B9EDC17
[*] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[+] Looks like we are good to go!

**Comment by staaldraad** [comment]
Brilliant! I'm so happy to hear that - always happy to help :smile: 

Nice thing with Outlook, you can leave out both `domain` and `username`. This will also work:
```go run ruler.go --email username@outlook.com check```

Thanks for sticking it out for two weeks, next give me a shout and I'll do my best to help (time allowing)

Happy pwning!

**Comment by VirtualSeeker** [comment]
Hi, I am coming again to seek your help.

**Comment by staaldraad** [comment]
Hi! So it seems like the autodiscover response has completed, and then it tries to connect to 10.14.78.20 - which then refuses the connection.

can you check if a file has been created in *~/go/src/github.com/sensepost/ruler/logs* ? hopefully it has created the autodiscover record there, and we can manually change the end-point so that it works

**Comment by VirtualSeeker** [comment]
Hi, staaldraad. I didn't find any file created in ~/go/src/github.com/sensepost/ruler/logs. When I tested it using Test E-mail AutoConfiguration of OutLook. It seems everything is fine. Here is the report.

`<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
    <User>
      <DisplayName>username</DisplayName>
      <LegacyDN>/o=example/ou=Exchange Administrative Group (xxxxxxxxxxxxxxx)/cn=Recipients/cn=username</LegacyDN>
      <AutoDiscoverSMTPAddress>username@example.com</AutoDiscoverSMTPAddress>
      <DeploymentId>xxxxxxxxx</DeploymentId>
    </User>
    <Account>
      <AccountType>email</AccountType>
      <Action>settings</Action>
      <Protocol>
        <Type>EXCH</Type>
        <Server>xxxxxxxxxxxx.example.com</Server>
        <ServerDN>/o=example/ou=Exchange Administrative Group (xxxxxxxxxxxxxxx)/cn=Configuration/cn=Servers/cn=xxxxxxxxxxxx.example.com</ServerDN>
        <ServerVersion>xxxxxx</ServerVersion>
        <MdbDN>/o=example/ou=Exchange Administrative Group (xxxxxxxxxxxxxxx)/cn=Configuration/cn=Servers/cn=xxxxxxxxxxxx.example.com/cn=Microsoft Private MDB</MdbDN>
        <PublicFolderServer>xxxxxxxxxxxx.example.com</PublicFolderServer>
        <AD>xxxxxxxxxxxx.example.com</AD>
        <ASUrl>https://mail.example.com/EWS/Exchange.asmx</ASUrl>
        <EwsUrl>https://mail.example.com/EWS/Exchange.asmx</EwsUrl>
        <EcpUrl>https://xxxx.example.com/ecp/</EcpUrl>
        <EcpUrl-um>?p=customize/voicemail.aspx&amp;exsvurl=1</EcpUrl-um>
        <EcpUrl-aggr>?p=personalsettings/EmailSubscriptions.slab&amp;exsvurl=1</EcpUrl-aggr>
        <EcpUrl-mt>PersonalSettings/DeliveryReport.aspx?exsvurl=1&amp;IsOWA=&lt;IsOWA&gt;&amp;MsgID=&lt;MsgID&gt;&amp;Mbx=&lt;Mbx&gt;</EcpUrl-mt>
        <EcpUrl-ret>?p=organize/xxxx.xxxx&amp;exsvurl=1</EcpUrl-ret>
        <EcpUrl-sms>?p=sms/xxxx.xxxx&amp;exsvurl=1</EcpUrl-sms>
        <OOFUrl>https://mail.example.com/EWS/Exchange.asmx</OOFUrl>
        <UMUrl>https://mail.example.com/EWS/UM2007Legacy.asmx</UMUrl>
        <OABUrl>http://xxxx.example.com/oab/xxxxxxxxxxxx/</OABUrl>
      </Protocol>
      <Protocol>
        <Type>EXPR</Type>
        <Server>mail.example.com</Server>
        <SSL>On</SSL>
        <AuthPackage>Ntlm</AuthPackage>
        <ASUrl>https://mail.example.com/EWS/Exchange.asmx</ASUrl>
        <EwsUrl>https://mail.example.com/EWS/Exchange.asmx</EwsUrl>
        <EcpUrl>https://xxxx.example.com/ecp/</EcpUrl>
        <EcpUrl-um>?p=customize/voicemail.aspx&amp;exsvurl=1</EcpUrl-um>
        <EcpUrl-aggr>?p=personalsettings/EmailSubscriptions.slab&amp;exsvurl=1</EcpUrl-aggr>
        <EcpUrl-mt>PersonalSettings/DeliveryReport.aspx?exsvurl=1&amp;IsOWA=&lt;IsOWA&gt;&amp;MsgID=&lt;MsgID&gt;&amp;Mbx=&lt;Mbx&gt;</EcpUrl-mt>
        <EcpUrl-ret>?p=organize/xxxx.xxxx&amp;exsvurl=1</EcpUrl-ret>
        <EcpUrl-sms>?p=sms/xxxx.xxxx&amp;exsvurl=1</EcpUrl-sms>
        <OOFUrl>https://mail.example.com/EWS/Exchange.asmx</OOFUrl>
        <UMUrl>https://mail.example.com/EWS/xxxxxxxxxxxx.asmx</UMUrl>
        <OABUrl>https://xxxx.example.com/oab/xxxxxxxxxxxx/</OABUrl>
      </Protocol>
      <Protocol>
        <Type>WEB</Type>
        <Internal>
          <OWAUrl AuthenticationMethod="Basic, Ntlm, Fba, WindowsIntegrated">https://xxxx.example.com/owa/</OWAUrl>
          <Protocol>
            <Type>EXCH</Type>
            <ASUrl>https://mail.example.com/EWS/Exchange.asmx</ASUrl>
          </Protocol>
        </Internal>
        <External>
          <OWAUrl AuthenticationMethod="Fba">https://xxxx.example.com/owa/</OWAUrl>
          <Protocol>
            <Type>EXPR</Type>
            <ASUrl>https://mail.example.com/EWS/Exchange.asmx</ASUrl>
          </Protocol>
        </External>
      </Protocol>
    </Account>
  </Response>
</Autodiscover>`

**Comment by staaldraad** [comment]
Ok, so you'll have to go the manual config route.. 

From the above autodiscover, you'll need the "LegacyDN" it will be this: 
```
/o=example/ou=Exchange Administrative Group (xxxxxxxxxxxxxxx)/cn=Recipients/cn=username
```
You'll also need the Mailbox, it will be the value after the `?` and before the `:` from this:
```
https://mail.example.com/rpc/rpcproxy.dll?xxxxxx.example.com:6001
```

the config file will look like this:
```
username: "username"
email: "email@example.com"
password: "password"
hash: ""
domain: ""
userdn: "/o=example/ou=Exchange Administrative Group (xxxxxxxxxxxxxxx)/cn=Recipients/cn=username"
mailbox: "xxxx@example.com"
rpcurl: "https://autodiscover.example.com/rpc/rpcproxy.dll"
rpc: true 
rpcencrypt: true
ntlm: true 
mapiurl: "https://outlook.office365.com/mapi/emsmdb/"
```

You'll obviously need to replace the username, email and password values. The other values to change are the `userdn` and the `mailbox`. 

save the config file, for example at */tmp/config.yml* and then use it:
```go run ruler.go --config /tmp/config.yml --verbose check```

**Comment by X1n9** [comment]
Hi
I always get this error :

go run ruler.go --email demo@test.fr form display
Password: 
[+] Retrieving MAPI/HTTP info
ERROR: 2017/07/25 12:17:08 The autodiscover service request did not complete.
access denied. Please check your credential
exit status 255 or 250.
----------------------------------
And my password is very true 
--------

and  i tried to use check 
--url https://autodiscover.my_email_com/autodiscover/autodiscover.xml [ this url i can access]--verbose check
--------

still

access denied. Please check your credential
exit status 255 or 250.

and i tried to use wireshark to Capture http request, 
and then return a 403 response .. some thing may wrong ??

**Comment by staaldraad** [comment]
Hi

Could you please check that you are supplying the correct ```--email <>``` and ```--username <>```. The username must be able to access the email. 

You can additionally try forcing basic authentication by using ```--basic```.
You can also include the domain, using ```--domain <domain>```

**Comment by X1n9** [comment]
3q ur idea 

i'm sure my pwd is correct and 

try `go run ruler.go -e xxx@xx.com -p xxxx --basic`  & `go run ruler.go  --basic -e xxx@xx.com -p xxxx` &  `go run ruler.go  --basic -u xxx@xx.com -p xxxx`  Meet some problems...
then I get usage show
....emmmmm~~
