### ISSUE TITLE
Transport Layer Error MAPI

### ISSUE THREAD

**Issue by bandrel** [sensepost/ruler#43]
I was able to discover credentials via bruteforce, but I am not able to use them beyond the brute force.  All I seem to get is the transport error occurred.  

The system is using o365 and ADFS.  

```
localhost:~/go/src/github.com/sensepost/ruler# go run ruler.go --nocache --o365 --debug --verbose --username first.last@<domain>.com --email first.last@<domain>.com -p <redacted> c
[*] Autodiscover step 0 - URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://outlook.office365.com/mapi/emsmdb/?MailboxId=<redacted>@<domain>.com
[*] MAPI AddressBook URL found:  https://outlook.office365.com/mapi/nspi/?MailboxId=<redacted>@<domain>.com
ERROR: 2017/07/25 16:16:01 mapi: a transport layer error occurred. Got a protocol error response: 
exit status 255

```

**Comment by staaldraad** [comment]
Hi!

First thoughts, with o365, typically they username isn't necessary (even with ADFS, in my experience). Since you've already discovered the autodiscover record, this should work:

```
go run ruler.go --o365 --debug --verbose  --email first.last@<domain>.com -p <redacted> check
```
I think with the --username there, ruler tries to do some NTLM against outlook.office365.com, where all that is required is basicAuth.

**Comment by bandrel** [comment]
I get the same error when removing the --username

**Comment by staaldraad** [comment]
hmm, seems I'm wrong.. Just tried against my o365 domain, no ADFS though. and **--username ** didn't impact it.

**Comment by staaldraad** [comment]
could you try with ```--rpc``` ? Doubt it is going to work, but might be worth a shot

**Comment by bandrel** [comment]
YOU ARE MY HERO.  I swear I tried this before, but now I get a "good to go" response.

**Comment by staaldraad** [comment]
Woot! happy pwnage :+1: 

hahaha.. this must be my week.. yet another one to my "I do not understand computers" list. Brilliant! 

p.s
I know this is asking a **LOT** but if at all possible, with heavy **redaction**, could you share the autodiscover record that got written to *logs/email_domain.cache* ? 

My email is etienne [at] sensepost.com 
- PGP key here: https://keys.sensepost.com/pks/lookup?op=get&search=etienne%40sensepost.com
