### ISSUE TITLE
hash option

### ISSUE THREAD

**Issue by l0x2a** [sensepost/ruler#44]
Maybe this is more a sort of 'user issue'. I am trying to use the --hash option on my o365 account without any luck. The hash is from an Responder.py capture:
[SMB] NTLMv2-SSP Client   : 1.2.3.94
[SMB] NTLMv2-SSP Username : MYDOM\User1
[SMB] NTLMv2-SSP Hash     : User1::MYDOM:1122334455667788:7447C51D9EF52FE10B1573xxxxxxxxx:0101000000000000B135E4754509D3011A45A6F59427EFD10000000002000A0053004D0042003100320001000A0053004D0042003100450004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D004200310045000800300030000000000000000100000000200000DD43E55E39E6DFF3AB439630A55FE258EF4C812C3F5AC136E1AC43A651A725390A001000000000000000000000000000000000000900260063006900660073002F00350022002E003200300030002E003100380035002E003100390031000000000000000000
I can't figure out the right part or format of that hash to put it in the ruler --hash option. I always get an authentication failed. Thanx in advance!

**Comment by staaldraad** [comment]
Hi!

The answer is two-fold;

1) The NTLMv2-SSP hash from responder won't work here, as it is not the raw NTLM hash, rather the net-ntlm hash. Ruler requires the raw NTLM, where-as the net-ntlm has already been hashed with the challenge (1122334455667788) 

2) My tests of the --hash has been against non-office365 environments. Apart from the ADFS component of o365, the authentication used is actually basic auth, meaning you need the clear-text password. With the ADFS it might be that some auth happens against an on premise server, and this would succeed with the hash. However, when the hand-off to o365 happens (post autodiscover), the auth would fail. Well, at least in the setups I have tested.

Hope that clarifies things!

**Comment by l0x2a** [comment]
Yes, it does, definitely! Thanx a lot!
