### ISSUE TITLE
Empty HTTP Response 

### ISSUE THREAD

**Issue by passwordleak** [sensepost/ruler#46]
I am testing this in a corporate environment. Also, it detects http rather than https, and http is turned off, so I have to add the url manually. 

root@kali:/opt/ruler# ./ruler --email test.user@test.com --username "test user" --url 'https://autodiscover.test.com/autodiscover/autodiscover.xml' --verbose check
Password:
[*] Autodiscover step 0 - URL: https://autodiscover.test.com/autodiscover/autodiscover.xml
[*] MAPI URL found:  https://outlook.test.com/mapi/emsmdb/?MailboxId=xxx@test.com
[*] MAPI AddressBook URL found:  https://outlook.test.com/mapi/nspi/?MailboxId=xxx@test.com
[*] v
ERROR: 2017/08/01 03:32:21 mapi: a transport layer error occurred. mapi: a transport layer error occurred. Empty HTTP Response

**Comment by staaldraad** [comment]
Hi!

I'm not too sure why this would be the case, especially since the autodiscover record seems to return correctly. You could try force RPC, as it's possible MAPI/HTTP isn't available.

```./ruler --email test.uers@test.com --username "test" --url "" --nocache --rpc --verbose check```

**Comment by passwordleak** [comment]
Thanks! Using RPC does work for everything except for the address book, which results in 

root@kali:/opt/ruler# ./ruler --email test.user@test.com --username "test" --url 'xxx' --verbose --rpc --nocache abk list
Password:
[*] RPC/HTTP forced, trying RPC/HTTP
[*] Autodiscover step 0 - URL: xxx
[*] RPC URL set: xxx
[*] Setting up channels
[+] Binding to RPC
[*] User DN:  xxx
[*] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[*] Let's play addressbook
ERROR: 2017/08/02 21:03:57 Only MAPI/HTTP is currently supported for addressbook interaction
[*] And disconnecting from server

However, I can create and active forms which is the most important part.

**Comment by staaldraad** [comment]
Great! Happy to hear it worked.

I still have to find time to implement the address book over RPC, it requires a fair chunk of work unfortunately :(

If you would be up for it, could you send (anonomised of course) copy of the autodiscover file? It should be found in *logs/email_address_domain.cache*

It could help me narrow down why MAPI/HTTP was presented as an option, but didn't work.

email: etienne [at] sensepost.com

Thanks!
