### ISSUE TITLE
Static Hostname "RULER" 

### ISSUE THREAD

**Issue by passwordleak** [sensepost/ruler#47]
I was just checking the logs to look for defenses, and I realized that the hostname is always "RULER," even when I change the user agent, which is also "ruler." 

From an attacker perspective, this obviously limits value as the defender can just look for hostname RULER events, so I grepped for "ruler" but could not find any relevant code, so I think it may be in a binary file or something. Of course skids will still use the default so defenses can still pick up on them. 

I'm wondering if this "RULER" hostname can be changed.

**Comment by staaldraad** [comment]
Brilliant! I've been waiting for a year to have someone ask this question :)

The hostname and the user-agent were hard-coded to give blue-teams a starting point. Basically a skiddy "canary" 

I've buried the hostname in the supporting NTLM library; https://github.com/staaldraad/go-ntlm - more specifically, in ntlmv1.go and ntlmv2.go.

```am.Workstation, _ = CreateStringPayload("RULER")```

Awesome that you've dug in and looked into this!

**Comment by lnxg33k** [comment]
Any plans to parameterize the workstation name along with the User-Agent (for all HTTP(s) requests) ?!

**Comment by staaldraad** [comment]
Nope sorry, not thinking of it at present :) 
Happy to accept PRs though!
