### ISSUE TITLE
[Bruteforcing] fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by Gilks** [sensepost/ruler#55]
When bruteforcing with ruler you will often time receive [this](https://gist.github.com/Gilks/e8826f2af80dfe01c596849635382a57) stack trace. If you rerun the same command it will eventually work. There appears to be some form of a race condition. Here is the one liner I am using:

    ruler --o365 --url http://autodiscover.your_company_here.com/autodiscover/autodiscover.xml brute --users emails.txt --passwords passwords.txt --verbose

After some digging, the problematic code appears to be located in `autodiscover/brute.go`. The problem seems to be that the code tries to unlock a semaphore while it's already unlocked. I can't seem to find the exact condition that causes this. With that said, if you place a `time.Sleep` right before `sem` is called it seems to patch the issue:

	for ui, u := range usernames {
		if u == "" || p == "" {
			continue
		}
		time.Sleep(time.Millisecond * 500) // patches mutex error
		sem <- true
		go func(u string, p string, i int) {
			defer func() { <-sem }()
			out := connect(autodiscoverURL, u, p, basic, insecure)
			out.Index = i

This is just a hack, it doesn't fix the underlying logic error or I would have submitted this as a PR. Do you have any idea what would cause this?

System and software info:

    Linux dev-box 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

    go version go1.9 linux/amd64

    ruler version 2.1.6

**Comment by staaldraad** [comment]
Hi! Thank you for a really detailed report :+1:

I’ve got a fix for this bug in the next release. It’s exactly as you say, the mutex tries to unlock even though it has been unlocked. The fix I’ve made is similar to yours, there is a slight delay added and I’ve also fixed the http client to close the connection more reliably, which was part of the problem.

I’ll retest my fix tomorrow to make sure it is good to go. The new code will be pushed in about two weeks, just need patch Tuesday to pass.

In the meantime, one of my colleagues has reported that leaving out --verbose helps with this issue. Alternatively lowering the ```concurrency = 5 ``` to ```concurrency = 3``` on line 26 of brute.go helps. Dropping it to 1 definitely fixes it, but that kind of defeats the point of having a multi-threaded brute ;)

Thanks again, I really appreciate the report and the amount of detail.

Cheers

**Comment by staaldraad** [comment]
Fixed with https://github.com/sensepost/ruler/pull/56
