### ISSUE TITLE
Delay / attempts are ignored

### ISSUE THREAD

**Issue by RedSec-Shay** [sensepost/ruler#60]
Not sure If I'm doing something wrong but the Delay / attempts flags arent working for me:

`./ruler --domain XXXXXXXX.com --insecure brute --users /root/tools/XX/users2.txt --passwords /root/tools/XX/pass.txt --attempts 1 --delay 35  -v

[+] Starting bruteforce
[+] Trying to Autodiscover domain
[x] Failed: user1:Password1!
[x] Failed: user2:Password1!
[x] Failed: user3:Password1!
[x] Failed: user4:Password1!
[x] Failed: user5:Password1!
[x] Failed: user6:Password1!
[x] Failed: user7:Password1!
[x] Failed: user8:Password1!
[x] Failed: user9:Password1!`

all those attempts happened in less than 3 sec instead of taking ~315 sec ( 9 users * 35 sec delay)
expected behavior would be try user1 , sleep for 35 sec , try user2 , etc..

Thanks in Advance

**Comment by staaldraad** [comment]
Hi!

The attempts is "password attempts per user". This means that each user will have the password attempted. The delay will kick in when a second password is attempted.

There isn’t a way to limit the attempts between users.

Hope this makes sense?

**Comment by RedSec-Shay** [comment]
Got it , thank you for clarifying .
We have seen more and more organizations detecting source IP based on amount of fail logins per minutes  . 
One solution would be to outlive the detection timeout . just something to keep in mind :)
