### ISSUE TITLE
An RPC probelem

### ISSUE THREAD

**Issue by zhouzhouzouzou** [sensepost/ruler#62]
I had a problem when I use ruler. And I can visit my website https://mail.domain.com and owa

[+] Retrieving MAPI/HTTP info
ERROR: 11:31:58 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. mapi: a transport layer error occurred. Couldn't setup RPC channel - RPC Setup Err: dial tcp :443: connectex: No connection could be made because the target machine actively refused it.
exit status 4294967295

**Comment by zhouzhouzouzou** [comment]
Though I can visit my website of my exchange server and owa

**Comment by staaldraad** [comment]
Hi

> No connection could be made because the target machine actively refused it.
exit status 

It seems like the host isn't accepting connections at the RPC end-point. It is likely that RPC is only configured for internal hosts. If you run with `--verbose` you'll see the RPC URL that Ruler tries to connect to.
