### ISSUE TITLE
Some about config.yml

### ISSUE THREAD

**Issue by SleepyKoalaHSC** [sensepost/ruler#64]
Hi!

I have read the issue "No autodiscover.xml" and edited my config:

> username: "Administrator"
email: "Administrator@codingkoala.com"
password: "password"
domain: "codingkoala"
userdn: "/o=First Organization/ou=Exchange Administrative Group ‎(FYDIBOHF23SPDLT)‎/cn=Recipients/cn=Administrator96b"
mailbox: "7367e46a-18d2-4aed-943f-cb315cc6e67d@codingkoala.com"
rpcurl: "https://192.168.179.150/rpc/rpcproxy.dll"
rpc: true
rpcencrypt: true
mapiurl: ""

I couldn't find GUID from OWA, so I get it from Exchange Management Shell.

And I get the following error:

> C:\Users\Administrator\Desktop>ruler --config config.yml check
ERROR: 13:20:53 ruler.go:29: mapi: a transport layer error occurred. Post ?Mailb
oxId=7367e46a-18d2-4aed-943f-cb315cc6e67d@codingkoala.com: Get ?MailboxId=7367e4
6a-18d2-4aed-943f-cb315cc6e67d@codingkoala.com: unsupported protocol scheme ""

Is there something wrong with GUID? 

Thank you.

**Comment by staaldraad** [comment]
Hi! 

That all looks correct, for some reason it seems to be trying to do a `GET ?Mailboxid...` instead of `GET rpcproxy.dll?Mailboxid`

And I think the reason for this might be an extremely silly one...
in your config, could you add: `ntlm: true` before the `mapiurl: ""`

> username: "Administrator"
email: "Administrator@codingkoala.com"
password: "password"
domain: "codingkoala"
userdn: "/o=First Organization/ou=Exchange Administrative Group ‎(FYDIBOHF23SPDLT)‎/cn=Recipients/cn=Administrator96b"
mailbox: "7367e46a-18d2-4aed-943f-cb315cc6e67d@codingkoala.com"
rpcurl: "https://192.168.179.150/rpc/rpcproxy.dll"
rpc: true
rpcencrypt: true
ntlm: true
mapiurl: ""

The yaml parsing I've done isn't great ;)

**Comment by SleepyKoalaHSC** [comment]
Thanks for your reply!

I added `ntlm:true` . It said I have an authentication error. So I changed it to false.

Then another error...

> C:\Users\Administrator\Desktop>ruler --config config.yml check
[+] Binding to RPC
ERROR: 20:17:51 rpctransport.go:574: RPC Timeout
ERROR: 20:17:51 ruler.go:29: mapi: a transport layer error occurred. An error oc
curred setting up RPC. Invalid HTTP response:
[!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
html xmlns="http://www.w3.org/1999/xhtml"
head
title  IIS 7.5 Detailed Error -]

(I deleted '<>' because it may be concealed)

It seems that setting owa host as rpcurl `rpcurl: "https://192.168.179.150/rpc/rpcproxy.dll"`  is not right.

**Comment by staaldraad** [comment]
finding RPC on the OWA host is a common situation but not guaranteed unfortunately. It looks like you are on an internal network, so it might be that RPC isn't available over HTTP. Internal configs are usually to use RPC/TCP (which ruler doesn't support)

if you check the headers from that response, or you try go to the OWA URL in a browser through a proxy like Burp, you could check if there is an `X-FEServer` header. that could point you to another host that might have /rpc/rpcproxy.dll available

**Comment by Villyli** [comment]
Hi!
Is my error the same reason(an internal network)?

[+] Binding to RPC
ERROR: 15:23:40 rpctransport.go:574: RPC Timeout
ERROR: 15:24:52 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. Invalid HTTP response: [HTTP/1.0 503 RPC Error: 6ba]

Ruler always makes my server crash. But my RPC service seemed work fine before I execute ruler by config.yml. 
 Do I have to use a proxy?

**Comment by staaldraad** [comment]
Hi @Villyli 

By "my server crash" do you mean the actual exchange server? The RPC service is returning a 503 error, indicating an internal server error for RPC. You could try changing the 
`ntlm: true` to `ntlm: false` - which will likely give different behaviour. It could also be that you require a vaild `domain: domainhere`
