### ISSUE TITLE
Request: Option to show/dump MAPI autodiscover

### ISSUE THREAD

**Issue by dirkjanm** [sensepost/ruler#65]
Hi,

First of all, thanks for the nice tool! I've been playing with it recently and ran into some (minor) issues, so I'll open some issues/requests :)

The current autodiscover command only requests the "regular" autodiscover XML, which returns the RPC urls. It would be nice to have an option to also request/dump the MAPI one.
It can be accomplished currently by changing https://github.com/sensepost/ruler/blob/658fb1b3af7bb05e4d1415bdf66ba66c7422bba7/ruler.go#L99, but it would be nicer if this was possible without having to edit the source.

**Comment by staaldraad** [comment]
Hi @dirkjanm ! Thanks for these 😄 

I'll have a look at fixing / improving when I've got some time. This one is definitely an easy one to do, and the others could be done with cli flags.

I will comment separately on the Internal/External one

**Comment by staaldraad** [comment]
I've added a `--mapi`  flag to the `autodiscover` command.

This can be found in the `dev-improvements` branch. I've only got an Outlook based account to test on but should be working fine. I'll merge if you can confirm it hasn't broken anything :smile:

**Comment by dirkjanm** [comment]
Seems to work here as well, thanks!
