### ISSUE TITLE
Config parameter overwritten inside function

### ISSUE THREAD

**Issue by dirkjanm** [sensepost/ruler#67]
When I specify the `basic` flag to enforce basic authentication, this gets stored in the session object. However when ruler uses autodiscovery, this config seems to be passed (referenced? I'm new to Go) on to the SessionConfig property.
This property is then written to around here:
https://github.com/sensepost/ruler/blob/a07f8f02a949b6375c1575eedfe910441d5b47a7/autodiscover/autodiscover.go#L347

When this config is then used in followup functions, the property no longer has its original value. In my case this caused the `basic` flag to switch to false halfway, causing subsequent requests to no longer be done with basic auth.

There may be other occurences of this in the code, but this is the only one I came across so far.

**Comment by staaldraad** [comment]
I've pushed a fix that should prevent overwriting of the `--basic` flag but keep the underlying logic of updating Ruler to use Basic Auth if it detects this during autodiscover.

I'll need some testing before merging this as it has a good chance of breaking things :smile:
