### ISSUE TITLE
Re-opening the minutes/seconds issue for the "delay" parameter.

### ISSUE THREAD

**Issue by L3vi47h4N** [sensepost/ruler#68]
Why was https://github.com/sensepost/ruler/pull/61 closed?

In ruler.go it incorrectly states in the help output that the "delay" parameter is measured in seconds.

In autodiscover.go you can see that the time duration is measured in minutes. It also states that it delays for "minutes":

https://github.com/sensepost/ruler/blob/a07f8f02a949b6375c1575eedfe910441d5b47a7/autodiscover/brute.go#L193

https://github.com/sensepost/ruler/blob/a07f8f02a949b6375c1575eedfe910441d5b47a7/autodiscover/brute.go#L194

Please consider reevaluating and merging this PR.

**Comment by staaldraad** [comment]
Updated this as part of bigger adjustments. 

Thanks for pointing out the discrepancy :+1:
