### ISSUE TITLE
Problem running inserteed vbscript in Outlook 2010

### ISSUE THREAD

**Issue by billyjayserres** [sensepost/ruler#69]
I'm trying to insert a vbscript using 'command' option with no success.E-mail delivered successfully but i haven't achieved to make vbscript work.

**Comment by staaldraad** [comment]
Hi @billyjayserres 

Ruler seems to be working correctly here, given that the whole process completes and the email arrives in the inbox. Remember that forms require a small degree of user interaction, unless the `--rule` option is used. Please see the wiki: https://github.com/sensepost/ruler/wiki/Forms#trigger-form-with-a-rule

It could also be that forms have been patched in this instance, explaining why the vbscript doesn't trigger.

good luck!
