### ISSUE TITLE
Feature Request: Allow URL for OWA to be specified

### ISSUE THREAD

**Issue by mubix** [sensepost/ruler#7]
If I can find the OWA site, but AutoDiscover isn't being agreeable is there a way to simply specify the MAPI URL?

**Comment by staaldraad** [comment]
Not at the moment, but I can add that in. 

You'll also require the User DN (/o=First Organization/ou=Exchange Administrative Group(blah)/cn=Recipients/cn=blahblah)

Just curious what is your method for retrieving the MAPI URL? Or is autodiscover working with manual request, but failing with ruler?

**Comment by staaldraad** [comment]
I've pushed a version to dev that allows bypassing of autodiscover.
Requires two new cmdline params, `-mapiUrl` and `-userDN`

```
-user "" -pass superduper -email "blah@outlook.com" -mapiUrl https://outlook.office365.com/mapi/emsmdb/\?MailboxId\=0000000d-fef9-00000-0000-000000000000@outlook.com -display -userDN "/o=First Organization/ou=Exchange Administrative Group(FYDIBOHF231111)/cn=Recipients/cn=0003BF0000000" -domain outlook.com
```

There is a big rewrite happening at the moment, so please keep any feature requests coming!

**Comment by mubix** [comment]
Didn't realize I would need the mailbox ID / UserDN, basically in a scenario where OWA is available but autodiscover isn't and trying to figure out if I can use the `ruler` tool to add the rules or if I'm just going to have to use the manual process

**Comment by staaldraad** [comment]
mmmm, haven't seen a way to do it without getting those values through autodiscover. It would be interesting to see how Outlook is pulling those values. My gut says that MAPI/HTTP isn't supported in this case, thus `ruler` would fail, unfortunately.

**Comment by staaldraad** [comment]
This isn't possible without knowing the LegacyDN. It might be possible to do through EWS but I'm closing this for now.

**Comment by mubix** [comment]
@staaldraad ever find a way to get the information via EWS? I'm in a very similar situation once again.

**Comment by staaldraad** [comment]
Hi @mubix 

As far as I can recall, I didn't find anything in EWS, the best I was able to do was to find some of the values exposed through OWA (although some of this isn't available in newer versions).

Wrote some docs here: https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file and this issue also discusses some of the options: https://github.com/sensepost/ruler/issues/31#issuecomment-299459847

Hope this helps. I'll go back to my notes to see if I did find something in EWS and I've simply forgotten 😂
