### ISSUE TITLE
some trouble when began

### ISSUE THREAD

**Issue by admin0day** [sensepost/ruler#70]
when root try"go run ruler.go -h",is come this words:
ruler.go:15:2: cannot find package "github.com/howeyc/gopass" in any of:
	/usr/local/go/src/github.com/howeyc/gopass (from $GOROOT)
	/root/go/src/github.com/howeyc/gopass (from $GOPATH)
ruler.go:16:2: cannot find package "github.com/sensepost/ruler/autodiscover" in any of:
	/usr/local/go/src/github.com/sensepost/ruler/autodiscover (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/autodiscover (from $GOPATH)
ruler.go:17:2: cannot find package "github.com/sensepost/ruler/forms" in any of:
	/usr/local/go/src/github.com/sensepost/ruler/forms (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/forms (from $GOPATH)
ruler.go:18:2: cannot find package "github.com/sensepost/ruler/mapi" in any of:
	/usr/local/go/src/github.com/sensepost/ruler/mapi (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/mapi (from $GOPATH)
ruler.go:19:2: cannot find package "github.com/sensepost/ruler/utils" in any of:
	/usr/local/go/src/github.com/sensepost/ruler/utils (from $GOROOT)
	/root/go/src/github.com/sensepost/ruler/utils (from $GOPATH)
ruler.go:20:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/local/go/src/github.com/urfave/cli (from $GOROOT)
	/root/go/src/github.com/urfave/cli (from $GOPATH)
root@kali:~/Tools/PentestTools/AutoTools/ruler# go version
go version go1.10 linux/arm
as u can see,my go version,so how can i fix this problem,thx for your time.

**Comment by staaldraad** [comment]
hi!

It looks like you are missing a dependency. You should be able to resolve this with:

`go get github.com/howeyc/gopass`
