### ISSUE TITLE
Command is too large error !

### ISSUE THREAD

**Issue by billyjayserres** [sensepost/ruler#72]
There is an issue with payload's size. I create a payload but ruler does not accept it displaying an error message  "Command is too large. Maximum command size is 4096 characters"
. 
Thank you in advance.

**Comment by staaldraad** [comment]
Hi!

Yes, forms are limited to 4096 characters. The reason for this is outlined in the post describing the attack on the [Sensepost blog](https://sensepost.com/blog/2017/outlook-forms-and-shells/)

> When Ruler generates the new form, it searches through form template for our “MAGIC” token and replaces this with the supplied payload. For now, this means that the payload size is limited to 4096 bytes, which should be more than enough for creating a useful payload. This means the standard base64 encoded Empire launcher should fit. But we are hackers, with 4096 bytes you should be able to do A LOT of interesting things.

This boils down to the fact that I would need to reverse the forms format and create a custom parser to allow arbitrary payload sizes. Being _lazy_ I went for the hardcoded entry :)

There is no plan to alter this.

Good luck! 👍
