### ISSUE TITLE
Plans to support o365 that is enforcing 2FA?

### ISSUE THREAD

**Issue by grandmerchant** [sensepost/ruler#73]
I've recently encountered some o365 portals that require an SMS authentication code. Are there any plans to update ruler to prompt for the 2FA code after asking for a password when running commands? Currently it seems to just fail with a bad authentication error.

**Comment by staaldraad** [comment]
Hi @grandmerchant 

Not at this time. Last time I dug into it, the 2FA required an "App specific password" to be generated for Outlook/Mobile (the older versions at least). So it could be possible to [generate this in the interface](https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183) and use that.
