### ISSUE TITLE
Sporadic mapi  "ruler.go:29: mapi: a transport layer error occurred "

### ISSUE THREAD

**Issue by bigrob69** [sensepost/ruler#74]
Hi Staaldraad

I have an interesting issue accessing a client MAPI instance. Initially the following is displayed for attempting to add a form 

_root@localhost:/opt# ./ruler-linux64 --o365 --debug --verbose --basic --noencrypt  --email user@domain.com -p xxxxxx form add --suffix super --input /home/www/input.txt --send
[+] Found cached Autodiscover record. Using this (use --nocache to force new lookup)
[*] MAPI URL found:  https://xxxxx.exchangemail.co.za/mapi/emsmdb/?MailboxId=1ca365f5-b4d1-4283-xxxxxxxxxx6cbe@domain.com
[*] MAPI AddressBook URL found:  https://xxxx.exchangemail.co.za/mapi/nspi/?MailboxId=1ca365f5-bxxxxxxxx.bd7-ba67e9ec6cbe@domain.com_

_ERROR: 08:39:48 ruler.go:29: mapi: a transport layer error occurred. Got a protocol error response: 
root@localhost:/opt#_ 

However , if I continue to re-attempt I get a little further , as per below before getting the same error.

_[+] Found cached Autodiscover record. Using this (use --nocache to force new lookup)
[*] MAPI URL found:  https://xxx.exchangemail.co.za/mapi/emsmdb/?MailboxId=xxxxxx4283-bbd7-ba67e9ec6cbe@domain.com
[*] MAPI AddressBook URL found:  https://xxxxxx.exchangemail.co.za/mapi/nspi/?MailboxId=xxxxxx-b4d1-42..83-bbd7-ba67e9ec6cbe@domain.com
[*] User DN:  /o=First Organization/ou=Exchange Administrative Group (FYDIxxxxxxxxLT)/cn=Recipients/cn=2f2398707ff542cfa2e8e0xxxxxxx
[*] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox_

_[*] Verifying that form does not exist.

ERROR: 08:52:44 ruler.go:29: mapi: a transport layer error occurred. Got a protocol error response: 
[*] And disconnecting from server_

The same process occurs for homepage interaction. Eventually it works. With regard to the ABK - i get get to about 15% before the error occurs.  Cant get the forms to go any further. 

thanks
rob

**Comment by staaldraad** [comment]
Hi @bigrob69 !

Thanks for the report. This will require some digging, my gut feel is that it is something to do with "fragmentation" of the responses from the server. Initially I thought this might be in RPC/HTTP because that is where I've had to deal with the fragmentation before and not in MAPI/HTTP. 

I'll dig through the code and specification when I get a bit of time and see how I could implement the fragmentation logic (the current approach is "_give me as much data as possible in a single response_")

**Comment by bigrob69** [comment]
Thanks for the reply and the assistance.

Please let me know if you need any further data or testing from my side.

I can confirm as per the screen that its definitely MAPI.


​

**Comment by staaldraad** [comment]
@bigrob69 👋 hey!

The new release 2.4.0 contains a fix for some fragmentation issues. Hopefully this has resolved this problem, if you still have access to the environment causing the problems, please give it a try 👍
