### ISSUE TITLE
The way to get PR_BODY or PR_MESSAGE_ATTACHMENTS 

### ISSUE THREAD

**Issue by ysq110** [sensepost/ruler#76]
Hi

I'm interesting about the great tool you create called "Ruler", but i met some problems. Some properties can not be fetched correctly, like PR_BODY (0x1000) or PR_MESSAGE_ATTACHMENTS (0x0E13). Is there a way to help me solve these questions?

Thank you very much!

**Comment by staaldraad** [comment]
Hi!

It seems like you are trying the `forms` functionality. Could you please provide the error output? I haven't seen an issue with those properties before. There are a LARGE number of things that could be causing it unfortunately :(

**Comment by ysq110** [comment]
There is a function named "GetMessage" in mapi/mapi.go , when we tried to get properties like "PR_BODY (0x1000)" or "PR_MESSAGE_ATTACHMENTS (0x0E13)" from messages in "INBOX" folder, it could not return the correct value of these properties. 
![example](https://user-images.githubusercontent.com/38522945/39090827-765b7ce8-461b-11e8-8406-41a49ee07c02.jpeg)
After searching the reference of MAPI funcions, fetching PR_BODY we supposed to get an UTF-8 string (the same as PR_TITLE), but it returns nothing. After that, we pass an empty column as propertytag to fetch all properies of the message and print each propery's value type, but we still can't find it.
Could you tell me your email address, so i can send more pics and infomations to you :-)
