### ISSUE TITLE
600 error

### ISSUE THREAD

**Issue by qiyidefeng** [sensepost/ruler#79]
I testet the latest src on my own exchange server with the command as follows 
```go run ruler.go --url https://mail.abc.edu.cn/autodiscover/autodiscover.xml -u user1 -p 1qaz2wsx@ --verbose -k c```
The password is right, but i still got 600 error
```[*] Autodiscover step 0 - URL: https://mail.abc.edu.cn/autodiscover/autodiscover.xml
ERROR: 10:25:20 ruler.go:29: The autodiscover service responded with an error.
Invalid Request
exit status 4294967295
```

When I testet it in the browser, the error was as follows:
```<Autodiscover>\n
<Response>
  <Error Time="10:33:57.9189914" Id="4224698814">
    <ErrorCode>600</ErrorCode>
    <Message>Invalid Request</Message>
    <DebugData/>
  </Error>
</Response>
</Autodiscover>
```
What's the reason?

**Comment by staaldraad** [comment]
Hi!

It seems like you have left out the email address for the user. This is required by the autodiscover service. If you include this, the 600 error should go away.
