### ISSUE TITLE
Panic (runtime error) when using parameter --insecure

### ISSUE THREAD

**Issue by falcon-lnhg** [sensepost/ruler#80]
The tool has been working fine for bruteforcing and other functionality, without using the --insecure flag. Today I ran into a server with an invalid certificate, and when trying to use --isecure got a panic (runtime error) message. Here is the information I see:

Request where the invalid cert is identified:
`root@server:~/go/src/github.com/sensepost/ruler# go run ruler.go -d domain.com -u user1 -p Password1 -e user1@domain.com --url https://autodiscover.domain.com/autodiscover/autodiscover.xml check
ERROR: 17:35:10 ruler.go:29: The autodiscover service request did not complete.
Post https://autodiscover.domain.com/autodiscover/autodiscover.xml: Get https://autodiscover.domain.com/autodiscover/autodiscover.xml: x509: certificate signed by unknown authority
exit status 255`

Request where the --invalid flag generates error:
`root@server:~/go/src/github.com/sensepost/ruler# go run ruler.go -d domain.com --insecure -u user1 -p Password1 -e user1@domain.com --url https://autodiscover.domain.com/autodiscover/autodiscover.xml check
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6e649f]`

`goroutine 1 [running]:
github.com/staaldraad/go-ntlm/ntlm.(*V1ClientSession).ProcessChallengeMessage(0xc420182000, 0xc42024a120, 0x8a, 0xc42024a120)
        /root/go/src/github.com/staaldraad/go-ntlm/ntlm/ntlmv1.go:402 +0x15f
github.com/sensepost/ruler/http-ntlm.NtlmTransport.RoundTrip(0x7ffcf5628975, 0x9, 0x7ffcf562898d, 0xc, 0x7ffcf562899d, 0x9, 0x0, 0x0, 0xa54e40, 0x0, ...)
        /root/go/src/github.com/sensepost/ruler/http-ntlm/ntlmtransport.go:115 +0x5e8
net/http.send(0xc420170100, 0x86aa00, 0xc42014f1f0, 0x0, 0x0, 0x0, 0xc4200ac098, 0x0, 0xc420165ac8, 0x1)
        /usr/lib/go-1.10/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc420099a10, 0xc420170100, 0x0, 0x0, 0x0, 0xc4200ac098, 0x0, 0x1, 0xc4200aa7c0)
        /usr/lib/go-1.10/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc420099a10, 0xc420170100, 0x10, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/http/client.go:615 +0x28d
github.com/sensepost/ruler/autodiscover.autodiscover(0x7ffcf56289c7, 0x3c, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:313 +0x406
github.com/sensepost/ruler/autodiscover.MAPIDiscover(0x7ffcf56289c7, 0x3c, 0x16, 0x23, 0x0, 0x4, 0xc4200a6240)
        /root/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:237 +0x108
github.com/sensepost/ruler/autodiscover.GetMapiHTTP(0x7ffcf56289aa, 0x16, 0x7ffcf56289c7, 0x3c, 0x0, 0x0, 0x0, 0x1, 0xc4200a3278, 0x0)
        /root/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:77 +0x359
main.connect(0xc4200ec9a0, 0x81db7c, 0xc4201666c8)
        /root/go/src/github.com/sensepost/ruler/ruler.go:446 +0x1ad0
main.main.func5(0xc4200ec9a0, 0xc420133100, 0xc4200ec9a0)
        /root/go/src/github.com/sensepost/ruler/ruler.go:1357 +0x2f
github.com/urfave/cli.HandleAction(0x79cca0, 0x839620, 0xc4200ec9a0, 0x0, 0xc420133140)
        /root/go/src/github.com/urfave/cli/app.go:501 +0xc8
github.com/urfave/cli.Command.Run(0x81db2c, 0x5, 0x0, 0x0, 0xc420096ca0, 0x1, 0x1, 0x8333b1, 0x42, 0x0, ...)
        /root/go/src/github.com/urfave/cli/command.go:165 +0x47d
github.com/urfave/cli.(*App).Run(0xc4201501c0, 0xc4200a2270, 0xd, 0xd, 0x0, 0x0)
        /root/go/src/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
        /root/go/src/github.com/sensepost/ruler/ruler.go:1778 +0x3331
exit status 2
test`

Any help is greatly appreciated

**Comment by staaldraad** [comment]
Hi!

The error seems to be occurring in the NTLM negotiation. The server is either not supplying, or supplying an invalid Version string for NTLM. This results in an error in the ntlm library, at https://github.com/staaldraad/go-ntlm/blob/master/ntlm/ntlmv1.go#L402

Without access to the server / raw messages it is impossible to provide a solution for why this is happening.
