### ISSUE TITLE
search using phrase

### ISSUE THREAD

**Issue by bandrel** [sensepost/ruler#82]
When using the `search` command multiple words in the `term` field are not processed as either a phrase or processed as either OR or AND operator. Searches just fail to match known content.

Example Email contents
> I love ruler!

using the commands 
`search --term love` OR
`search --term 'love'` 
both result in a match, but 
`search --term 'I love'` OR
`search --term I\ love` OR
`search --term I --term love`
do not return any results.

**Comment by staaldraad** [comment]
😄 the search functionality definitely needs some love. I started implementing the search protocol but got busy/lazy and didn't take it further than the single term match. There is a whole seperate set of datastructs to control this. The skeleton logic is there, it just needs to be glued together in the right order. 

https://github.com/sensepost/ruler/blob/master/mapi/restrictionDatastructs.go#L50

I'll try clear some time to get to this 👍

**Comment by staaldraad** [comment]
I've updated the search, in my testing it now matches on phrases with spaces.

I'll still keep "Enhanced search syntax" allowing for OR and AND as a future improvement.
