### ISSUE TITLE
--proxy when using brute

### ISSUE THREAD

**Issue by bandrel** [sensepost/ruler#83]
It does not appear that the `--proxy` option is used with the brute option. It does however use the proxy for the check option.

**Comment by staaldraad** [comment]
Thanks!

This should be a simple one to add, I'll try get to it asap.

**Comment by staaldraad** [comment]
I've added `--proxy` support for brute-force. This is available in the dev-improvements branch. This hasn't been tested, the code compiles 👍 but I haven't fired it off in anger. If you get a chance to test, please let me know!

**Comment by staaldraad** [comment]
Merging this into master
