### ISSUE TITLE
Attempt to use the username when bruteforcing accounts - Enhancement

### ISSUE THREAD

**Issue by mlinton** [sensepost/ruler#84]
The suggestion is that in addition to the password file provided, an option/switch to attempt to use the username as the password when password-spraying accounts.

**Comment by staaldraad** [comment]
Hi 

Thanks for the suggestion. I've added this in https://github.com/sensepost/ruler/commit/022c146be66ab030f90577f7db0688ba9138df8f

Merging into master now.

Cheers
