### ISSUE TITLE
Implement stats while brute-forcing 

### ISSUE THREAD

**Issue by unl1k3ly** [sensepost/ruler#85]
Hi, 

First of all, great awesome tool!

Would be possible to implement stats of a running brute force list so we can ensure how far are we getting to the end of the list ?

I mean, something like, every minute or so... just throwing some numbers around to see how many password were completed outta the given list.

Cheers

**Comment by staaldraad** [comment]
Hi

I added a stats check in https://github.com/sensepost/ruler/commit/022c146be66ab030f90577f7db0688ba9138df8f

Merging this now.
