### ISSUE TITLE
Ability to use usernamelist as a password. 

### ISSUE THREAD

**Issue by unl1k3ly** [sensepost/ruler#87]
Hi, 

Would be possible to use the given username list as a password ? It's very often admins set username's pw as username! 

Cheers

**Comment by staaldraad** [comment]
Hi, this has been implemented in https://github.com/sensepost/ruler/issues/84

The brute force will attempt the username as a password. Simply supply your user list and a password list with only 1 entry. Alternatively it should be pretty simple to create a username:username list using standard Linux command line tools.

Something like: 
```
awk 'FNR==NR{a[$1]=$1 FS $2;next}{ print $0”:”a[$1]}' usernames.txt usernames.txt
```

Cheers
