### ISSUE TITLE
Freeze on RPC Bind like #19

### ISSUE THREAD

**Issue by LeonMessi** [sensepost/ruler#89]
Hello, thanks for sharing this fantastic tool ! I am a beginner on network security. Recently, I am testing the Ruler. I encounter the same issue that is described by funoverip in #19, like this:

`C:\GOPATH\src\github.com\sensepost\ruler>go run ruler.go --domain worldcup.com --username worldcup\administrator --email administrator@worldcup.com --verbose --basic --nocache check
Password:

[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://autodiscover.worldcup.com/autodiscover/autodiscover.xml
[*] RPC URL set: https://server2012.worldcup.com/rpc/rpcproxy.dll?55bf30cf-cc89-443e-a272-7a54fffa0386@worldcup.com:6001
[*] Setting up channels
[+] Binding to RPC
exit status 2`
(99% cpu / freeze on RPC Bind)

When I test the vector form and homepage, this problem still exists.

I hope I can get your help.
My Ruler's version is:  2.2.0 
Exchange server 2013 x64 build on windows server 2012 r2 , DC is build on windows server 2008 R2

**Comment by staaldraad** [comment]
Hi

Could you try change the username to `administrator` and not `worldcup\administrator`. Also you likely don't need `--domain worldcup.com`.

I think those auth creds are working fine for the HTTP authentication but the inner RPC authentication is likely failing.

**Comment by LeonMessi** [comment]
Thank you for your reply.  
I tried this way, but it can't pass the authentication of autodiscover service.
Errors go like below:
`C:\GOPATH\src\github.com\sensepost\ruler>go run ruler.go --domain worldcup.com -
-username administrator --email administrator@worldcup.com --verbose --basic --n
ocache check
Password:
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://autodiscover.worldcup.com/autodiscover/au
todiscover.xml
ERROR: 15:46:32 ruler.go:29: The autodiscover service request did not complete.
Access denied. Check your credentials
exit status 4294967295

C:\GOPATH\src\github.com\sensepost\ruler>go run ruler.go --username administrato
r --email administrator@worldcup.com --verbose --basic --nocache check
Password:
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://autodiscover.worldcup.com/autodiscover/au
todiscover.xml
ERROR: 15:47:04 ruler.go:29: The autodiscover service request did not complete.
Access denied. Check your credentials
exit status 4294967295`

In addition, I think if the inner RPC authentication failure occurs, it will return a notice about RPC authentication failure. But I didn't get such notice.

**Comment by LeonMessi** [comment]
I wonder if it is because I didn't turn on some certain services on Exchange server that the "Freeze on RPC Bind" errors occured .

**Comment by staaldraad** [comment]
It could be that, configuring Exchange is a real pain. You could try add `--debug` in there, but I don't think it will actually give you anything additional since the freeze means there is no error, so no output of the last received packet. 

There is also the option to run with `--noencrypt` which won't sign and encrypt the RPC messages, which might not be enabled on the Exchange server.
