### ISSUE TITLE
Brute Force isn't working

### ISSUE THREAD

**Issue by tanujain** [sensepost/ruler#93]
I am trying the brute force functionality. Even if I give the correct the password, it's giving me failed attempt message. 
go run ruler.go --o365  --email 'xyz@abc.com' --url https://url/autodiscover.xml --basic brute --users users.txt --passwords pass.txt --verbose --delay 0

Display and everything else is working fine. What I might be missing here?

**Comment by staaldraad** [comment]
You do not require the `--email` or `--basic` in the brute command. Also I see you are targeting O365, in which case you should ensure that the usernames in the users.txt consist of the full email address of the target users.

**Comment by tanujain** [comment]
the users.txt has the full email address. 
I tried with 
"go run ruler.go --o365  --url https://url/autodiscover.xml  brute --users users.txt --passwords pass.txt --verbose" but still getting failed.
