### ISSUE TITLE
Brute Force tried Username as pass

### ISSUE THREAD

**Issue by ah2501** [sensepost/ruler#96]
Is there a switch to disable this madness? Is it as simple as commenting out the user_as_pass param and if statement, or is there an undocumented switch somewhere to stop this from happening. It's not very good practice to just add that without a measure to disable it....

**Comment by staaldraad** [comment]
Hi

As you said, you can just change `user_as_pass = true` to `user_as_pass = false` https://github.com/sensepost/ruler/blob/master/autodiscover/brute.go#L40.

Would gladly accept a PR that adds a command-line option to control that param.

**Comment by ah2501** [comment]
OK, that didn't seem to work for me when i set it to false; it still went ahead and ran through the username list as password.
